import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 text-gray-800">
      <Link to="/" className="text-brand-600 text-sm hover:underline">← Back</Link>
      <h1 className="text-3xl font-bold mt-4 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: April 21, 2026</p>

      <div className="prose prose-sm max-w-none space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. Agreement</h2>
          <p>By creating an account or using ContractorPro, you agree to these Terms. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. The service</h2>
          <p>ContractorPro is a software tool that helps contractors manage estimates, leads, invoices, projects, and marketing content. Some features use AI (Anthropic Claude) via your own API key.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Account and payment</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must provide accurate information and keep your password confidential.</li>
            <li>ContractorPro is $29/month after a 7-day free trial, billed via Stripe.</li>
            <li>You can cancel anytime through the in-app billing portal. Cancellation takes effect at the end of the current billing period.</li>
            <li>Anthropic API usage is billed separately by Anthropic based on your own API key.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. Acceptable use</h2>
          <p>You agree not to use the service to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Violate any law or the rights of others.</li>
            <li>Send spam or unsolicited communications.</li>
            <li>Attempt to access other users' data or the service's infrastructure without authorization.</li>
            <li>Generate misleading, defamatory, or deceptive content.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Your content</h2>
          <p>You own the content you create in ContractorPro (estimates, invoices, etc.). By using the service, you grant us a limited license to store, display, and process that content solely to provide the service to you.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. AI-generated content</h2>
          <p>AI outputs are generated by Anthropic Claude based on your inputs. They may contain errors. You are responsible for reviewing and verifying AI-generated content before sending it to clients or using it in legal, financial, or regulated contexts.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Termination</h2>
          <p>We may suspend or terminate accounts that violate these Terms. You may close your account at any time.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">8. Disclaimers</h2>
          <p>The service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted availability or that the service is free of errors. You are responsible for maintaining your own backups of important business data.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">9. Limitation of liability</h2>
          <p>To the maximum extent permitted by law, our total liability for any claim arising from the service is limited to the amount you paid us in the preceding 12 months. We are not liable for indirect, incidental, or consequential damages.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">10. Changes</h2>
          <p>We may update these Terms. Continued use of the service after changes take effect constitutes acceptance. Material changes will be communicated by email or in-app notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">11. Contact</h2>
          <p>Questions: <a href="mailto:nyokas444@gmail.com" className="text-brand-600 hover:underline">nyokas444@gmail.com</a></p>
        </section>
      </div>
    </div>
  )
}
